trigger:
- main

parameters:
- name: targetEnv
  type: string
  default: dev
  values:
  - dev
  - prod

- name: azureServiceConnection
  type: string
  default: Azure-Service-Connection-Sub

variables:
# DEV
- ${{ if eq(parameters.targetEnv, 'dev') }}:
  - group: variable_iScalaArchive
  - name: resourceGroupName
    value: rg-iscala-archive-dev
  - name: storageAccount
    value: stiscalasnapshotdev
  - name: rgLocation
    value: swedencentral

# PROD
- ${{ if eq(parameters.targetEnv, 'prod') }}:
  - group: variable_iScalaArchive-prod
  - name: resourceGroupName
    value: rg-iscala-archive-prod
  - name: rgLocation
    value: swedencentral
  - name: containerName
    value: snapshot


- name: deploymentPrincipalObjectId
  value: 94f97b9f-b688-4f99-a3ff-64e0e8a945d8

- name: storageAccountResourceId
  value: /subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.Storage/storageAccounts/$(storageAccount)

stages:
- stage: Deploy
  displayName: Deploy ${{ parameters.targetEnv }}
  jobs:

  - ${{ if eq(parameters.targetEnv, 'dev') }}:
    - job: DeployDev
      displayName: Deploy DEV
      pool:
        name: easec-pool
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: Validate snapshot storage exists
        inputs:
          azureSubscription: ${{ parameters.azureServiceConnection }}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            set -euo pipefail
            az storage account show -n "$(storageAccount)" -g "$(resourceGroupName)" -o none
            echo "Snapshot storage exists."

  - ${{ if eq(parameters.targetEnv, 'prod') }}:
    - deployment: DeployProd
      displayName: Deploy PROD (requires approval)
      environment: iscala-archive-prod
      pool:
        name: easec-pool
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self

            - task: AzureCLI@2
              displayName: Ensure resources exist
              inputs:
                azureSubscription: ${{ parameters.azureServiceConnection }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  set -e
                  RESOURCE_GROUP="$(resourceGroupName)"
                  LOCATION="$(rgLocation)"
                  STORAGE_ACCOUNT="$(storageAccount)"
                  CONTAINER_NAME="$(containerName)"

                  echo "Checking resource group: $RESOURCE_GROUP"
                  if [ "$(az group exists --name "$RESOURCE_GROUP")" = "true" ]; then
                    echo "Resource group already exists: "$RESOURCE_GROUP"
                  else
                    echo "Creating resource group: "$RESOURCE_GROUP"
                    az group create \
                        --name "$RESOURCE_GROUP" \
                        --location "$LOCATION" \
                        --output none
                  fi